### ISSUE TITLE
Mehr Dokumentation zur Installation/Requirements

### ISSUE THREAD

**Issue by AluhutBackbar** [holzmaster/node-pr0gramm-api#1]
Hallo!

Leider beinhaltet die ReadMe keine Informationen über notwendige Anpassungen an NodeJS.
Ich habe die aktuelle Version (10.8) heruntergeladen, das Module aus der ReadMe installiert und werde mit 

    (node:9804) ExperimentalWarning: The ESM module loader is experimental.   
    SyntaxError: The requested module 'pr0gramm-api' does not provide an export named 'Pr0grammAPI'

begrüßt. Es fehlt leider jegliche Hilfestellung bezüglich etwaiger Abhängigkeiten oder Voraussetzungen. Meine "Haupt-Datei" lautet `index.mjs` und ich starte node mit `--experimental-modules`, um ES6-Module zu laden.

Der Code in der index.mjs-Datei lautet 

```
import { Pr0grammAPI, ItemFlags } from "pr0gramm-api";

const api = Pr0grammAPI.createWithCookies();
 
async function main() {
    let mainItems = await api.items.getItems({
        promoted: true,
        flags: ItemFlags.All
    });
    console.dir(mainItems.items);
 
    let loginResponse = await api.user.login("cha0s", "stahl0fen80");
    if(!loginResponse.success) {
        console.log("Could not log in :(");
        if(loginResponse.ban !== null) {
            console.log("You are banned. Reason:");
            console.log(loginResponse.ban.reason);
            return;
        }
    }
}
main();
```

Leider ist das Modul so nicht OOTB benutzbar.

**Comment by holzmaster** [comment]
Wenn du es mit JS benutzt, darfst du keine ES-Module verwenden. Das TS wird nach CommonJS kompiliert, weshalb du bei purem JS über das Standard-`require` arbeiten müsstest.

Wenn du TS nutzt, solltest du als Target Module System CommonJS auswählen.

ES-Module werde ich erst shoppen, wenn sie Node ohne Flag nativ kann.

**Comment by AluhutBackbar** [comment]
Danke, hat funktioniert!
