### ISSUE TITLE
Captchas beim Einloggen

### ISSUE THREAD

**Issue by Peter9751** [holzmaster/node-pr0gramm-api#11]
Hallo,

für den Login muss seit neustem zusätzlich ein Captcha gelöst werden.

Das sorgt dafür dass die Login Funktion nicht mehr funktioniert, jedoch weiß ich auch nicht wie man das Problem mit dem Captcha umgehen soll.

Zum Beispiel:
`const loginResponse = await api.user.login("cha0s", "stahl0fen80");`
gibt als Rückmeldung `error: 'invalidCaptcha'` zurück.

Da bleibt ja eigentlich nur noch das Importieren eines bestehenden Cookies aus dem Browser übrig um die Api verwenden zu können, oder?

**Comment by holzmaster** [comment]
Ja, das wäre eine Möglichkeit. Die andere wäre es, das Captcha dem User zur Verfügung zu stellen, damit es gelöst werden kann.

Man müsste definitiv was neues implementieren.

**Comment by Peter9751** [comment]
Kannst du mir denn ein Beispiel geben wie man das über Cookies macht?

Was ich versucht habe:
```js
const { Pr0grammAPI, NodeRequester, ItemFlags } = require("pr0gramm-api");

const requester = NodeRequester.create("https://pr0gramm.com", {pp: "Kurzer Code", me: "Langer Code"});
const api = Pr0grammAPI.create(requester);

api.items.getItemsNewer({
    newer: 100,
    flags: ItemFlags.All,
    promoted: false,
})
.then(response => console.log(response))
.catch(error => console.log(error));
```
Natürlich hab ich die Cookiewerte durch die aus dem Browser ersetzt.

Das müsste meines Verständnis nach funktionieren, leider kommt aber als Meldung 
```
Error: Forbidden
    at needle.then.res (C:\Entwicklung\Projekte\Pr0_Search\node_modules\pr0gramm-api\lib\requester\node.js:31:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
``` 
zurück.

Hast du ne Idee was ich anders machen könnte?

**Comment by Peter9751** [comment]
Das Problem mit den Cookies konnte ich jetzt lösen.

Needle scheint die Werte der Cookies nochmals zu URL encoden, wodurch sie verändert abgesendet wurden. Die Lösung ist also die Werte, die man in den Cookies übergeben möchte, zuerst zu URL-decoden.



Das heißt im obigen Beispiel
```js
const requester = NodeRequester.create("https://pr0gramm.com", {'me': '%7B%22t%22%3A0,%22lv%22%3A7431602559,%22n%22%3A%22Peter9751%22,%22id%22%3A%22a1b2c48c399ef6130a50f58c93cbe2f%22,%22a%22%3A0,%22pp%22%3A%22443d49ab%22,%22paid%22%3Afalse%7D'});
```
muss man bei dem 'me'-Cookie den Wert decodieren, also:
```js
const requester = NodeRequester.create("https://pr0gramm.com", {'me': '{"t":0,"lv":7431602559,"n":"Peter9751","id":"a1b2c48c399ef6130a50f58c93cbe2f","a":0,"pp":"443d49ab","paid":false}'});
```

Der 'pp'-Cookie wird wohl scheinbar nicht benötigt und kann weg gelassen werden.

**Comment by nikeee** [comment]
Alternativ habe ich jetzt angefangen, die oAuth-Schnittstelle zu implementieren. die Basis dafür sind die Projekte von @RundesBalli

Einmal das:
https://github.com/RundesBalli/pr0gramm-apiCall/blob/e49470faed1bd363c2db4b25f776f6c12d0643a6/apiCall.php#L68-L79
Und der Bondrucker:
https://github.com/RundesBalli/pr0gramm-bondrucker

Kann leider nicht testen, ob es funktioniert.

**Comment by holzmaster** [comment]
Alternativ habe ich jetzt angefangen, die oAuth-Schnittstelle zu implementieren. die Basis dafür sind die Projekte von @RundesBalli

Einmal das:
https://github.com/RundesBalli/pr0gramm-apiCall/blob/e49470faed1bd363c2db4b25f776f6c12d0643a6/apiCall.php#L68-L79
Und der Bondrucker:
https://github.com/RundesBalli/pr0gramm-bondrucker

Kann leider nicht testen, ob es funktioniert.

**Comment by RundesBalli** [comment]
Als kleine Ergänzung noch:
Man muss sich den `pr0-api-key` vorher erst besorgen:
https://github.com/RundesBalli/pr0gramm-bondrucker/blob/master/public/inc/auth.php#L75-L87 hier ersichtlich. Die `auth.php` ist die Callback-URL, welche ich versucht habe recht ausführlich zu dokumentieren (soweit ich die Dinge wusste).
Wie lange das Token gültig ist weiß ich allerdings nicht, da ich nur einmalig den Usernamen abfrage.

Vielleicht hilft das weiter ¯\_(ツ)_/¯

**Comment by RundesBalli** [comment]
Zur Token Gültigkeit kopiere ich einfach mal die PN, die ich @holzmaster geschickt habe:

```
Hallo holzmaster,

ich konnte in Erfahrung bringen, dass das Token:
https://github.com/RundesBalli/pr0gramm-bondrucker/blob/master/public/inc/auth.php#L78-L79
wohl dauerhaft Gültigkeit hat.

Bedenke aber, dass das Token ungültig werden KANN, wenn der User z.B. die Berechtigung entzieht (kommt wohl bald eine Unterseite in den Einstellungen wo man oAuth Sitzungen beenden kann).

Dachte mir dass ich dich das mal wissen lasse :-)

Viele Grüße
Balli
```

**Comment by Wenski** [comment]
@RundesBalli 
Ich bin gerade unfähig in deinem Code die Tokenabfrage abzulesen. Ich würde ggf. die Bibliothek von holzmaster zu ergänzen. 
Wie erzeuge ich als Benutzer ein gültiges Token, dass ich fortan zum anmelden nutzen kann um die Captchas zu vermeiden? 

Beste Grüße

**Comment by holzmaster** [comment]
Das ganze hat vielleicht etwas verwirrt.

Sofern du keinen oAuth-API-Key von den Admins hast, kommst du um das Captcha nicht herum. Diese Schnittstelle unterstützt die Node.js-API hier aber schon. Der Code dafür ist hier:
https://github.com/holzmaster/node-pr0gramm-api/blob/f97afce7e84aa1593d5d78b0c45d2c5e5acdfd9d/src/pr0gramm-api.ts#L441-L459
(userName ist dort noch falsch, das ist eigentlich eine kryptische UserID).

Hast du so einen Key nicht, musst du, um nicht jedes Mal ein Captcha eingeben zu müssen, deine Browser-Session impersonaten (siehe Kommentar von @Peter9751).

**Comment by holzmaster** [comment]
Bei meiner anderen API hat ein lieber User gerade Captchas implementiert:
https://github.com/holzmaster/OpenPr0gramm/pull/26

Ggf. können wir das einfach so übernehmen.

**Comment by holzmaster** [comment]
Captchas gehen nun. im README steht, wie man es verwendet.

Das Bild ist eine data-URL und kann deshalb direkt als `src` für eim `img`-Element verwendet werden.
