### ISSUE TITLE
npm package veraltet

### ISSUE THREAD

**Issue by vincentmathis** [holzmaster/node-pr0gramm-api#12]
`npm install pr0gramm-api`
installiert version 2.2.1 statt 3.0.0

Sollte im readme.md erwähnt werden, es stattdessen mit `npm install https://github....` zu installieren.

**Comment by holzmaster** [comment]
Die Version 3 hat noch den Tag @next.

Kann ich heute gern als release publishen.

**Comment by holzmaster** [comment]
`v3.0.0` wird jetzt gebaut und dann auch gepublished.
