### ISSUE TITLE
Wie filtert man nach Tags bzw. woher bekommt man tag ids.

### ISSUE THREAD

**Issue by vincentmathis** [holzmaster/node-pr0gramm-api#13]
Ich versuche items nach tags zu filtern aber bin mir nicht sicher, wie man das macht.
Oder woher ich die Tag.ID wissen soll.
Ich habe das probiert aber es kommt ein leeres array:

```js
  const tagOCSonntag = {
    id: 5851,
    tag: "OC-Sonntag"
  };

  const mainItems = await api.items.getItems({
    promoted: true,
    flags: ItemFlags.NSFW,
    tags: [tagOCSonntag]
  });
```

Wenn ich das hier versuche:
```js
api.tags.getDetails(3584682);
```
bekomme ich:
```
(node:14444) UnhandledPromiseRejectionWarning: Error: Forbidden
    at needle.then.res (D:\Users\vince\Projects\node-pr0-oc\node_modules\pr0gramm-api\lib\requester\node.js:31:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:14444) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:14444) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by holzmaster** [comment]
Der Typ vom Tag scheint auf den ersten Blick nicht zu stimmen. Ich glaube das sollte ein String sein (kein ganzes Objekt).

Dazu kommt, dass man ohne aktive Sitzung nur SFW anfragen kann. NSFW/NSFP/NSFL geht nur mit einem gültigen Session-Cookie (sonst 403).

**Comment by vincentmathis** [comment]
Ich bin davon ausgegangen, dass das `tags` Attribut der `getItems` Methode vom Typ `Tag[]` ist und habe das Interface `Tag` gesucht, welches so definiert ist:

```js
export interface Tag extends RatedElement {
    id: TagID;
    tag: string;
}
```

Daher dachte ich, man müsse eine TagID kennen und ein Object übergeben.
Das mit der Session-Cookie habe ich schon aus dem anderen Issue gesehen.

```js
  const mainItems = await api.items.getItems({
    promoted: true,
    flags: ItemFlags.NSFW,
    tags: ["Boobs"]
  });
```
Scheint zu funktionieren.

Aber hat man mehrere Tags, erhält mein ein leeres array:
```js
  const mainItems = await api.items.getItems({
    promoted: true,
    flags: ItemFlags.NSFW,
    tags: ["Boobs", "selfie"]
  });
```

**Comment by holzmaster** [comment]
> Ich bin davon ausgegangen, dass das tags Attribut der getItems Methode vom Typ Tag[] ist 

Genau die Stelle meinte ich mit "alschem Typ". Ist jetzt korrigiert.

Bitte überprüfe mal, ob es jetzt geht.

**Comment by vincentmathis** [comment]
Ist jetzt eine Liste von Strings und funktioniert soweit ich das sehen kann auch.

Jedoch ist die Suche nicht exact.
```js
const itemStream = api.items.walkStreamNewer({
  newer: 0,
  flags: ItemFlags.NSFW,
  promoted: false,
  tags: ["OC Content"]
});
```
liefert auch items mit folgenden tags: `[ 'content', 'digital', 'free', 'nsfw', 'tits' ]`

Ich weiß nicht ob pr0s API exaktes matching überhaupt anbietet.
Alternativ versuche ich es gerade mit

```js
for await (const item of itemStream) {
  const response = await api.items.getInfo(item.id);
  const itemTags = response.tags.map(ele => ele.tag);
  if (itemTags.includes("OC Content")) {
    ...
  }
}
```
