### ISSUE TITLE
Unterstützung für weitere Ränge

### ISSUE THREAD

**Issue by thahnen** [holzmaster/node-pr0gramm-api#4]
In [**src/common-types.ts**](https://github.com/holzmaster/node-pr0gramm-api/blob/master/src/common-types.ts) fehlen noch:

- Alt-Moderator
- Community-Helfer
- Mittelaltschwuchtel

als Raenge in UserMark.
Ich denke mal die unterschiedlichen Werte sind nicht an pr0gramms eigene API geknoepft?

**Comment by holzmaster** [comment]
Fehlt auch noch, danke!
